# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c75eab95536c4e465ce5250aebfe4aa49e7f817357c9579c9f3243079523284adf3e6ab85e59d0f4048b99942c14dc321fae14ad0902a1961d66d369caefb82d

test:
  secret_key_base: e30170456b59694235f284918aeb0e04a60819219d2ca2a1666533ba888b588642469d6bb92a08a78ccf8b72c6c05e695a5c73652767d30708faa1f5ffe736ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
